// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: get_storage_node.proto

package edu.usfca.cs.dfs;

public final class GetStorageNode {
  private GetStorageNode() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface getStorageNodeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:getStorageNode)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 port = 1;</code>
     */
    int getPort();
  }
  /**
   * Protobuf type {@code getStorageNode}
   */
  public  static final class getStorageNode extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:getStorageNode)
      getStorageNodeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use getStorageNode.newBuilder() to construct.
    private getStorageNode(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private getStorageNode() {
      port_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private getStorageNode(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              port_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.usfca.cs.dfs.GetStorageNode.internal_static_getStorageNode_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.usfca.cs.dfs.GetStorageNode.internal_static_getStorageNode_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.usfca.cs.dfs.GetStorageNode.getStorageNode.class, edu.usfca.cs.dfs.GetStorageNode.getStorageNode.Builder.class);
    }

    public static final int PORT_FIELD_NUMBER = 1;
    private int port_;
    /**
     * <code>int32 port = 1;</code>
     */
    public int getPort() {
      return port_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (port_ != 0) {
        output.writeInt32(1, port_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (port_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, port_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof edu.usfca.cs.dfs.GetStorageNode.getStorageNode)) {
        return super.equals(obj);
      }
      edu.usfca.cs.dfs.GetStorageNode.getStorageNode other = (edu.usfca.cs.dfs.GetStorageNode.getStorageNode) obj;

      boolean result = true;
      result = result && (getPort()
          == other.getPort());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PORT_FIELD_NUMBER;
      hash = (53 * hash) + getPort();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static edu.usfca.cs.dfs.GetStorageNode.getStorageNode parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usfca.cs.dfs.GetStorageNode.getStorageNode parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.GetStorageNode.getStorageNode parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usfca.cs.dfs.GetStorageNode.getStorageNode parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.GetStorageNode.getStorageNode parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usfca.cs.dfs.GetStorageNode.getStorageNode parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.GetStorageNode.getStorageNode parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.usfca.cs.dfs.GetStorageNode.getStorageNode parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.GetStorageNode.getStorageNode parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static edu.usfca.cs.dfs.GetStorageNode.getStorageNode parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.GetStorageNode.getStorageNode parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.usfca.cs.dfs.GetStorageNode.getStorageNode parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(edu.usfca.cs.dfs.GetStorageNode.getStorageNode prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code getStorageNode}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:getStorageNode)
        edu.usfca.cs.dfs.GetStorageNode.getStorageNodeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.usfca.cs.dfs.GetStorageNode.internal_static_getStorageNode_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.usfca.cs.dfs.GetStorageNode.internal_static_getStorageNode_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.usfca.cs.dfs.GetStorageNode.getStorageNode.class, edu.usfca.cs.dfs.GetStorageNode.getStorageNode.Builder.class);
      }

      // Construct using edu.usfca.cs.dfs.GetStorageNode.getStorageNode.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        port_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.usfca.cs.dfs.GetStorageNode.internal_static_getStorageNode_descriptor;
      }

      public edu.usfca.cs.dfs.GetStorageNode.getStorageNode getDefaultInstanceForType() {
        return edu.usfca.cs.dfs.GetStorageNode.getStorageNode.getDefaultInstance();
      }

      public edu.usfca.cs.dfs.GetStorageNode.getStorageNode build() {
        edu.usfca.cs.dfs.GetStorageNode.getStorageNode result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public edu.usfca.cs.dfs.GetStorageNode.getStorageNode buildPartial() {
        edu.usfca.cs.dfs.GetStorageNode.getStorageNode result = new edu.usfca.cs.dfs.GetStorageNode.getStorageNode(this);
        result.port_ = port_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.usfca.cs.dfs.GetStorageNode.getStorageNode) {
          return mergeFrom((edu.usfca.cs.dfs.GetStorageNode.getStorageNode)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.usfca.cs.dfs.GetStorageNode.getStorageNode other) {
        if (other == edu.usfca.cs.dfs.GetStorageNode.getStorageNode.getDefaultInstance()) return this;
        if (other.getPort() != 0) {
          setPort(other.getPort());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        edu.usfca.cs.dfs.GetStorageNode.getStorageNode parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (edu.usfca.cs.dfs.GetStorageNode.getStorageNode) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int port_ ;
      /**
       * <code>int32 port = 1;</code>
       */
      public int getPort() {
        return port_;
      }
      /**
       * <code>int32 port = 1;</code>
       */
      public Builder setPort(int value) {
        
        port_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 port = 1;</code>
       */
      public Builder clearPort() {
        
        port_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:getStorageNode)
    }

    // @@protoc_insertion_point(class_scope:getStorageNode)
    private static final edu.usfca.cs.dfs.GetStorageNode.getStorageNode DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new edu.usfca.cs.dfs.GetStorageNode.getStorageNode();
    }

    public static edu.usfca.cs.dfs.GetStorageNode.getStorageNode getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<getStorageNode>
        PARSER = new com.google.protobuf.AbstractParser<getStorageNode>() {
      public getStorageNode parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new getStorageNode(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<getStorageNode> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<getStorageNode> getParserForType() {
      return PARSER;
    }

    public edu.usfca.cs.dfs.GetStorageNode.getStorageNode getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface storageNodesListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:storageNodesList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .getStorageNode portList = 1;</code>
     */
    java.util.List<edu.usfca.cs.dfs.GetStorageNode.getStorageNode> 
        getPortListList();
    /**
     * <code>repeated .getStorageNode portList = 1;</code>
     */
    edu.usfca.cs.dfs.GetStorageNode.getStorageNode getPortList(int index);
    /**
     * <code>repeated .getStorageNode portList = 1;</code>
     */
    int getPortListCount();
    /**
     * <code>repeated .getStorageNode portList = 1;</code>
     */
    java.util.List<? extends edu.usfca.cs.dfs.GetStorageNode.getStorageNodeOrBuilder> 
        getPortListOrBuilderList();
    /**
     * <code>repeated .getStorageNode portList = 1;</code>
     */
    edu.usfca.cs.dfs.GetStorageNode.getStorageNodeOrBuilder getPortListOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code storageNodesList}
   */
  public  static final class storageNodesList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:storageNodesList)
      storageNodesListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use storageNodesList.newBuilder() to construct.
    private storageNodesList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private storageNodesList() {
      portList_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private storageNodesList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                portList_ = new java.util.ArrayList<edu.usfca.cs.dfs.GetStorageNode.getStorageNode>();
                mutable_bitField0_ |= 0x00000001;
              }
              portList_.add(
                  input.readMessage(edu.usfca.cs.dfs.GetStorageNode.getStorageNode.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          portList_ = java.util.Collections.unmodifiableList(portList_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.usfca.cs.dfs.GetStorageNode.internal_static_storageNodesList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.usfca.cs.dfs.GetStorageNode.internal_static_storageNodesList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.usfca.cs.dfs.GetStorageNode.storageNodesList.class, edu.usfca.cs.dfs.GetStorageNode.storageNodesList.Builder.class);
    }

    public static final int PORTLIST_FIELD_NUMBER = 1;
    private java.util.List<edu.usfca.cs.dfs.GetStorageNode.getStorageNode> portList_;
    /**
     * <code>repeated .getStorageNode portList = 1;</code>
     */
    public java.util.List<edu.usfca.cs.dfs.GetStorageNode.getStorageNode> getPortListList() {
      return portList_;
    }
    /**
     * <code>repeated .getStorageNode portList = 1;</code>
     */
    public java.util.List<? extends edu.usfca.cs.dfs.GetStorageNode.getStorageNodeOrBuilder> 
        getPortListOrBuilderList() {
      return portList_;
    }
    /**
     * <code>repeated .getStorageNode portList = 1;</code>
     */
    public int getPortListCount() {
      return portList_.size();
    }
    /**
     * <code>repeated .getStorageNode portList = 1;</code>
     */
    public edu.usfca.cs.dfs.GetStorageNode.getStorageNode getPortList(int index) {
      return portList_.get(index);
    }
    /**
     * <code>repeated .getStorageNode portList = 1;</code>
     */
    public edu.usfca.cs.dfs.GetStorageNode.getStorageNodeOrBuilder getPortListOrBuilder(
        int index) {
      return portList_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < portList_.size(); i++) {
        output.writeMessage(1, portList_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < portList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, portList_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof edu.usfca.cs.dfs.GetStorageNode.storageNodesList)) {
        return super.equals(obj);
      }
      edu.usfca.cs.dfs.GetStorageNode.storageNodesList other = (edu.usfca.cs.dfs.GetStorageNode.storageNodesList) obj;

      boolean result = true;
      result = result && getPortListList()
          .equals(other.getPortListList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getPortListCount() > 0) {
        hash = (37 * hash) + PORTLIST_FIELD_NUMBER;
        hash = (53 * hash) + getPortListList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static edu.usfca.cs.dfs.GetStorageNode.storageNodesList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usfca.cs.dfs.GetStorageNode.storageNodesList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.GetStorageNode.storageNodesList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usfca.cs.dfs.GetStorageNode.storageNodesList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.GetStorageNode.storageNodesList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usfca.cs.dfs.GetStorageNode.storageNodesList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.GetStorageNode.storageNodesList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.usfca.cs.dfs.GetStorageNode.storageNodesList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.GetStorageNode.storageNodesList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static edu.usfca.cs.dfs.GetStorageNode.storageNodesList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.GetStorageNode.storageNodesList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.usfca.cs.dfs.GetStorageNode.storageNodesList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(edu.usfca.cs.dfs.GetStorageNode.storageNodesList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code storageNodesList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:storageNodesList)
        edu.usfca.cs.dfs.GetStorageNode.storageNodesListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.usfca.cs.dfs.GetStorageNode.internal_static_storageNodesList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.usfca.cs.dfs.GetStorageNode.internal_static_storageNodesList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.usfca.cs.dfs.GetStorageNode.storageNodesList.class, edu.usfca.cs.dfs.GetStorageNode.storageNodesList.Builder.class);
      }

      // Construct using edu.usfca.cs.dfs.GetStorageNode.storageNodesList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPortListFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (portListBuilder_ == null) {
          portList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          portListBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.usfca.cs.dfs.GetStorageNode.internal_static_storageNodesList_descriptor;
      }

      public edu.usfca.cs.dfs.GetStorageNode.storageNodesList getDefaultInstanceForType() {
        return edu.usfca.cs.dfs.GetStorageNode.storageNodesList.getDefaultInstance();
      }

      public edu.usfca.cs.dfs.GetStorageNode.storageNodesList build() {
        edu.usfca.cs.dfs.GetStorageNode.storageNodesList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public edu.usfca.cs.dfs.GetStorageNode.storageNodesList buildPartial() {
        edu.usfca.cs.dfs.GetStorageNode.storageNodesList result = new edu.usfca.cs.dfs.GetStorageNode.storageNodesList(this);
        int from_bitField0_ = bitField0_;
        if (portListBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            portList_ = java.util.Collections.unmodifiableList(portList_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.portList_ = portList_;
        } else {
          result.portList_ = portListBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.usfca.cs.dfs.GetStorageNode.storageNodesList) {
          return mergeFrom((edu.usfca.cs.dfs.GetStorageNode.storageNodesList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.usfca.cs.dfs.GetStorageNode.storageNodesList other) {
        if (other == edu.usfca.cs.dfs.GetStorageNode.storageNodesList.getDefaultInstance()) return this;
        if (portListBuilder_ == null) {
          if (!other.portList_.isEmpty()) {
            if (portList_.isEmpty()) {
              portList_ = other.portList_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePortListIsMutable();
              portList_.addAll(other.portList_);
            }
            onChanged();
          }
        } else {
          if (!other.portList_.isEmpty()) {
            if (portListBuilder_.isEmpty()) {
              portListBuilder_.dispose();
              portListBuilder_ = null;
              portList_ = other.portList_;
              bitField0_ = (bitField0_ & ~0x00000001);
              portListBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getPortListFieldBuilder() : null;
            } else {
              portListBuilder_.addAllMessages(other.portList_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        edu.usfca.cs.dfs.GetStorageNode.storageNodesList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (edu.usfca.cs.dfs.GetStorageNode.storageNodesList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<edu.usfca.cs.dfs.GetStorageNode.getStorageNode> portList_ =
        java.util.Collections.emptyList();
      private void ensurePortListIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          portList_ = new java.util.ArrayList<edu.usfca.cs.dfs.GetStorageNode.getStorageNode>(portList_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          edu.usfca.cs.dfs.GetStorageNode.getStorageNode, edu.usfca.cs.dfs.GetStorageNode.getStorageNode.Builder, edu.usfca.cs.dfs.GetStorageNode.getStorageNodeOrBuilder> portListBuilder_;

      /**
       * <code>repeated .getStorageNode portList = 1;</code>
       */
      public java.util.List<edu.usfca.cs.dfs.GetStorageNode.getStorageNode> getPortListList() {
        if (portListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(portList_);
        } else {
          return portListBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .getStorageNode portList = 1;</code>
       */
      public int getPortListCount() {
        if (portListBuilder_ == null) {
          return portList_.size();
        } else {
          return portListBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .getStorageNode portList = 1;</code>
       */
      public edu.usfca.cs.dfs.GetStorageNode.getStorageNode getPortList(int index) {
        if (portListBuilder_ == null) {
          return portList_.get(index);
        } else {
          return portListBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .getStorageNode portList = 1;</code>
       */
      public Builder setPortList(
          int index, edu.usfca.cs.dfs.GetStorageNode.getStorageNode value) {
        if (portListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePortListIsMutable();
          portList_.set(index, value);
          onChanged();
        } else {
          portListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .getStorageNode portList = 1;</code>
       */
      public Builder setPortList(
          int index, edu.usfca.cs.dfs.GetStorageNode.getStorageNode.Builder builderForValue) {
        if (portListBuilder_ == null) {
          ensurePortListIsMutable();
          portList_.set(index, builderForValue.build());
          onChanged();
        } else {
          portListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .getStorageNode portList = 1;</code>
       */
      public Builder addPortList(edu.usfca.cs.dfs.GetStorageNode.getStorageNode value) {
        if (portListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePortListIsMutable();
          portList_.add(value);
          onChanged();
        } else {
          portListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .getStorageNode portList = 1;</code>
       */
      public Builder addPortList(
          int index, edu.usfca.cs.dfs.GetStorageNode.getStorageNode value) {
        if (portListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePortListIsMutable();
          portList_.add(index, value);
          onChanged();
        } else {
          portListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .getStorageNode portList = 1;</code>
       */
      public Builder addPortList(
          edu.usfca.cs.dfs.GetStorageNode.getStorageNode.Builder builderForValue) {
        if (portListBuilder_ == null) {
          ensurePortListIsMutable();
          portList_.add(builderForValue.build());
          onChanged();
        } else {
          portListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .getStorageNode portList = 1;</code>
       */
      public Builder addPortList(
          int index, edu.usfca.cs.dfs.GetStorageNode.getStorageNode.Builder builderForValue) {
        if (portListBuilder_ == null) {
          ensurePortListIsMutable();
          portList_.add(index, builderForValue.build());
          onChanged();
        } else {
          portListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .getStorageNode portList = 1;</code>
       */
      public Builder addAllPortList(
          java.lang.Iterable<? extends edu.usfca.cs.dfs.GetStorageNode.getStorageNode> values) {
        if (portListBuilder_ == null) {
          ensurePortListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, portList_);
          onChanged();
        } else {
          portListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .getStorageNode portList = 1;</code>
       */
      public Builder clearPortList() {
        if (portListBuilder_ == null) {
          portList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          portListBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .getStorageNode portList = 1;</code>
       */
      public Builder removePortList(int index) {
        if (portListBuilder_ == null) {
          ensurePortListIsMutable();
          portList_.remove(index);
          onChanged();
        } else {
          portListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .getStorageNode portList = 1;</code>
       */
      public edu.usfca.cs.dfs.GetStorageNode.getStorageNode.Builder getPortListBuilder(
          int index) {
        return getPortListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .getStorageNode portList = 1;</code>
       */
      public edu.usfca.cs.dfs.GetStorageNode.getStorageNodeOrBuilder getPortListOrBuilder(
          int index) {
        if (portListBuilder_ == null) {
          return portList_.get(index);  } else {
          return portListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .getStorageNode portList = 1;</code>
       */
      public java.util.List<? extends edu.usfca.cs.dfs.GetStorageNode.getStorageNodeOrBuilder> 
           getPortListOrBuilderList() {
        if (portListBuilder_ != null) {
          return portListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(portList_);
        }
      }
      /**
       * <code>repeated .getStorageNode portList = 1;</code>
       */
      public edu.usfca.cs.dfs.GetStorageNode.getStorageNode.Builder addPortListBuilder() {
        return getPortListFieldBuilder().addBuilder(
            edu.usfca.cs.dfs.GetStorageNode.getStorageNode.getDefaultInstance());
      }
      /**
       * <code>repeated .getStorageNode portList = 1;</code>
       */
      public edu.usfca.cs.dfs.GetStorageNode.getStorageNode.Builder addPortListBuilder(
          int index) {
        return getPortListFieldBuilder().addBuilder(
            index, edu.usfca.cs.dfs.GetStorageNode.getStorageNode.getDefaultInstance());
      }
      /**
       * <code>repeated .getStorageNode portList = 1;</code>
       */
      public java.util.List<edu.usfca.cs.dfs.GetStorageNode.getStorageNode.Builder> 
           getPortListBuilderList() {
        return getPortListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          edu.usfca.cs.dfs.GetStorageNode.getStorageNode, edu.usfca.cs.dfs.GetStorageNode.getStorageNode.Builder, edu.usfca.cs.dfs.GetStorageNode.getStorageNodeOrBuilder> 
          getPortListFieldBuilder() {
        if (portListBuilder_ == null) {
          portListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              edu.usfca.cs.dfs.GetStorageNode.getStorageNode, edu.usfca.cs.dfs.GetStorageNode.getStorageNode.Builder, edu.usfca.cs.dfs.GetStorageNode.getStorageNodeOrBuilder>(
                  portList_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          portList_ = null;
        }
        return portListBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:storageNodesList)
    }

    // @@protoc_insertion_point(class_scope:storageNodesList)
    private static final edu.usfca.cs.dfs.GetStorageNode.storageNodesList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new edu.usfca.cs.dfs.GetStorageNode.storageNodesList();
    }

    public static edu.usfca.cs.dfs.GetStorageNode.storageNodesList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<storageNodesList>
        PARSER = new com.google.protobuf.AbstractParser<storageNodesList>() {
      public storageNodesList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new storageNodesList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<storageNodesList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<storageNodesList> getParserForType() {
      return PARSER;
    }

    public edu.usfca.cs.dfs.GetStorageNode.storageNodesList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_getStorageNode_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_getStorageNode_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_storageNodesList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_storageNodesList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026get_storage_node.proto\"\036\n\016getStorageNo" +
      "de\022\014\n\004port\030\001 \001(\005\"5\n\020storageNodesList\022!\n\010" +
      "portList\030\001 \003(\0132\017.getStorageNodeB\022\n\020edu.u" +
      "sfca.cs.dfsb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_getStorageNode_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_getStorageNode_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_getStorageNode_descriptor,
        new java.lang.String[] { "Port", });
    internal_static_storageNodesList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_storageNodesList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_storageNodesList_descriptor,
        new java.lang.String[] { "PortList", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
