// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: responses_to_storageNode.proto

package edu.usfca.cs.dfs;

public final class ResponsesToStorageNode {
  private ResponsesToStorageNode() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AcknowledgeEnrollmentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AcknowledgeEnrollment)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool success = 1;</code>
     */
    boolean getSuccess();
  }
  /**
   * <pre>
   *Controller
   * </pre>
   *
   * Protobuf type {@code AcknowledgeEnrollment}
   */
  public  static final class AcknowledgeEnrollment extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:AcknowledgeEnrollment)
      AcknowledgeEnrollmentOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AcknowledgeEnrollment.newBuilder() to construct.
    private AcknowledgeEnrollment(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AcknowledgeEnrollment() {
      success_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AcknowledgeEnrollment(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              success_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.usfca.cs.dfs.ResponsesToStorageNode.internal_static_AcknowledgeEnrollment_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.usfca.cs.dfs.ResponsesToStorageNode.internal_static_AcknowledgeEnrollment_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeEnrollment.class, edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeEnrollment.Builder.class);
    }

    public static final int SUCCESS_FIELD_NUMBER = 1;
    private boolean success_;
    /**
     * <code>bool success = 1;</code>
     */
    public boolean getSuccess() {
      return success_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (success_ != false) {
        output.writeBool(1, success_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (success_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, success_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeEnrollment)) {
        return super.equals(obj);
      }
      edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeEnrollment other = (edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeEnrollment) obj;

      boolean result = true;
      result = result && (getSuccess()
          == other.getSuccess());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getSuccess());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeEnrollment parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeEnrollment parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeEnrollment parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeEnrollment parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeEnrollment parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeEnrollment parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeEnrollment parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeEnrollment parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeEnrollment parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeEnrollment parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeEnrollment parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeEnrollment parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeEnrollment prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *Controller
     * </pre>
     *
     * Protobuf type {@code AcknowledgeEnrollment}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:AcknowledgeEnrollment)
        edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeEnrollmentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.usfca.cs.dfs.ResponsesToStorageNode.internal_static_AcknowledgeEnrollment_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.usfca.cs.dfs.ResponsesToStorageNode.internal_static_AcknowledgeEnrollment_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeEnrollment.class, edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeEnrollment.Builder.class);
      }

      // Construct using edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeEnrollment.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        success_ = false;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.usfca.cs.dfs.ResponsesToStorageNode.internal_static_AcknowledgeEnrollment_descriptor;
      }

      public edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeEnrollment getDefaultInstanceForType() {
        return edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeEnrollment.getDefaultInstance();
      }

      public edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeEnrollment build() {
        edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeEnrollment result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeEnrollment buildPartial() {
        edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeEnrollment result = new edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeEnrollment(this);
        result.success_ = success_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeEnrollment) {
          return mergeFrom((edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeEnrollment)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeEnrollment other) {
        if (other == edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeEnrollment.getDefaultInstance()) return this;
        if (other.getSuccess() != false) {
          setSuccess(other.getSuccess());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeEnrollment parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeEnrollment) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean success_ ;
      /**
       * <code>bool success = 1;</code>
       */
      public boolean getSuccess() {
        return success_;
      }
      /**
       * <code>bool success = 1;</code>
       */
      public Builder setSuccess(boolean value) {
        
        success_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool success = 1;</code>
       */
      public Builder clearSuccess() {
        
        success_ = false;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:AcknowledgeEnrollment)
    }

    // @@protoc_insertion_point(class_scope:AcknowledgeEnrollment)
    private static final edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeEnrollment DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeEnrollment();
    }

    public static edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeEnrollment getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AcknowledgeEnrollment>
        PARSER = new com.google.protobuf.AbstractParser<AcknowledgeEnrollment>() {
      public AcknowledgeEnrollment parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new AcknowledgeEnrollment(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AcknowledgeEnrollment> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AcknowledgeEnrollment> getParserForType() {
      return PARSER;
    }

    public edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeEnrollment getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AcknowledgeReadinessToSNOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AcknowledgeReadinessToSN)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool success = 1;</code>
     */
    boolean getSuccess();
  }
  /**
   * <pre>
   *StorageNode
   * </pre>
   *
   * Protobuf type {@code AcknowledgeReadinessToSN}
   */
  public  static final class AcknowledgeReadinessToSN extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:AcknowledgeReadinessToSN)
      AcknowledgeReadinessToSNOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AcknowledgeReadinessToSN.newBuilder() to construct.
    private AcknowledgeReadinessToSN(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AcknowledgeReadinessToSN() {
      success_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AcknowledgeReadinessToSN(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              success_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.usfca.cs.dfs.ResponsesToStorageNode.internal_static_AcknowledgeReadinessToSN_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.usfca.cs.dfs.ResponsesToStorageNode.internal_static_AcknowledgeReadinessToSN_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeReadinessToSN.class, edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeReadinessToSN.Builder.class);
    }

    public static final int SUCCESS_FIELD_NUMBER = 1;
    private boolean success_;
    /**
     * <code>bool success = 1;</code>
     */
    public boolean getSuccess() {
      return success_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (success_ != false) {
        output.writeBool(1, success_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (success_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, success_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeReadinessToSN)) {
        return super.equals(obj);
      }
      edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeReadinessToSN other = (edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeReadinessToSN) obj;

      boolean result = true;
      result = result && (getSuccess()
          == other.getSuccess());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getSuccess());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeReadinessToSN parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeReadinessToSN parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeReadinessToSN parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeReadinessToSN parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeReadinessToSN parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeReadinessToSN parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeReadinessToSN parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeReadinessToSN parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeReadinessToSN parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeReadinessToSN parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeReadinessToSN parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeReadinessToSN parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeReadinessToSN prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *StorageNode
     * </pre>
     *
     * Protobuf type {@code AcknowledgeReadinessToSN}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:AcknowledgeReadinessToSN)
        edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeReadinessToSNOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.usfca.cs.dfs.ResponsesToStorageNode.internal_static_AcknowledgeReadinessToSN_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.usfca.cs.dfs.ResponsesToStorageNode.internal_static_AcknowledgeReadinessToSN_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeReadinessToSN.class, edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeReadinessToSN.Builder.class);
      }

      // Construct using edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeReadinessToSN.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        success_ = false;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.usfca.cs.dfs.ResponsesToStorageNode.internal_static_AcknowledgeReadinessToSN_descriptor;
      }

      public edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeReadinessToSN getDefaultInstanceForType() {
        return edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeReadinessToSN.getDefaultInstance();
      }

      public edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeReadinessToSN build() {
        edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeReadinessToSN result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeReadinessToSN buildPartial() {
        edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeReadinessToSN result = new edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeReadinessToSN(this);
        result.success_ = success_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeReadinessToSN) {
          return mergeFrom((edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeReadinessToSN)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeReadinessToSN other) {
        if (other == edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeReadinessToSN.getDefaultInstance()) return this;
        if (other.getSuccess() != false) {
          setSuccess(other.getSuccess());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeReadinessToSN parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeReadinessToSN) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean success_ ;
      /**
       * <code>bool success = 1;</code>
       */
      public boolean getSuccess() {
        return success_;
      }
      /**
       * <code>bool success = 1;</code>
       */
      public Builder setSuccess(boolean value) {
        
        success_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool success = 1;</code>
       */
      public Builder clearSuccess() {
        
        success_ = false;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:AcknowledgeReadinessToSN)
    }

    // @@protoc_insertion_point(class_scope:AcknowledgeReadinessToSN)
    private static final edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeReadinessToSN DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeReadinessToSN();
    }

    public static edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeReadinessToSN getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AcknowledgeReadinessToSN>
        PARSER = new com.google.protobuf.AbstractParser<AcknowledgeReadinessToSN>() {
      public AcknowledgeReadinessToSN parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new AcknowledgeReadinessToSN(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AcknowledgeReadinessToSN> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AcknowledgeReadinessToSN> getParserForType() {
      return PARSER;
    }

    public edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeReadinessToSN getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResponsesToStorageNodeWrapperOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ResponsesToStorageNodeWrapper)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.AcknowledgeEnrollment AcknowledgeEnrollmentMsg = 1;</code>
     */
    boolean hasAcknowledgeEnrollmentMsg();
    /**
     * <code>.AcknowledgeEnrollment AcknowledgeEnrollmentMsg = 1;</code>
     */
    edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeEnrollment getAcknowledgeEnrollmentMsg();
    /**
     * <code>.AcknowledgeEnrollment AcknowledgeEnrollmentMsg = 1;</code>
     */
    edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeEnrollmentOrBuilder getAcknowledgeEnrollmentMsgOrBuilder();

    /**
     * <code>.AcknowledgeReadinessToSN AcknowledgeReadinessToSNMsg = 2;</code>
     */
    boolean hasAcknowledgeReadinessToSNMsg();
    /**
     * <code>.AcknowledgeReadinessToSN AcknowledgeReadinessToSNMsg = 2;</code>
     */
    edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeReadinessToSN getAcknowledgeReadinessToSNMsg();
    /**
     * <code>.AcknowledgeReadinessToSN AcknowledgeReadinessToSNMsg = 2;</code>
     */
    edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeReadinessToSNOrBuilder getAcknowledgeReadinessToSNMsgOrBuilder();

    public edu.usfca.cs.dfs.ResponsesToStorageNode.ResponsesToStorageNodeWrapper.MsgCase getMsgCase();
  }
  /**
   * Protobuf type {@code ResponsesToStorageNodeWrapper}
   */
  public  static final class ResponsesToStorageNodeWrapper extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ResponsesToStorageNodeWrapper)
      ResponsesToStorageNodeWrapperOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ResponsesToStorageNodeWrapper.newBuilder() to construct.
    private ResponsesToStorageNodeWrapper(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ResponsesToStorageNodeWrapper() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ResponsesToStorageNodeWrapper(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeEnrollment.Builder subBuilder = null;
              if (msgCase_ == 1) {
                subBuilder = ((edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeEnrollment) msg_).toBuilder();
              }
              msg_ =
                  input.readMessage(edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeEnrollment.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeEnrollment) msg_);
                msg_ = subBuilder.buildPartial();
              }
              msgCase_ = 1;
              break;
            }
            case 18: {
              edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeReadinessToSN.Builder subBuilder = null;
              if (msgCase_ == 2) {
                subBuilder = ((edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeReadinessToSN) msg_).toBuilder();
              }
              msg_ =
                  input.readMessage(edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeReadinessToSN.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeReadinessToSN) msg_);
                msg_ = subBuilder.buildPartial();
              }
              msgCase_ = 2;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.usfca.cs.dfs.ResponsesToStorageNode.internal_static_ResponsesToStorageNodeWrapper_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.usfca.cs.dfs.ResponsesToStorageNode.internal_static_ResponsesToStorageNodeWrapper_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.usfca.cs.dfs.ResponsesToStorageNode.ResponsesToStorageNodeWrapper.class, edu.usfca.cs.dfs.ResponsesToStorageNode.ResponsesToStorageNodeWrapper.Builder.class);
    }

    private int msgCase_ = 0;
    private java.lang.Object msg_;
    public enum MsgCase
        implements com.google.protobuf.Internal.EnumLite {
      ACKNOWLEDGEENROLLMENTMSG(1),
      ACKNOWLEDGEREADINESSTOSNMSG(2),
      MSG_NOT_SET(0);
      private final int value;
      private MsgCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static MsgCase valueOf(int value) {
        return forNumber(value);
      }

      public static MsgCase forNumber(int value) {
        switch (value) {
          case 1: return ACKNOWLEDGEENROLLMENTMSG;
          case 2: return ACKNOWLEDGEREADINESSTOSNMSG;
          case 0: return MSG_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public MsgCase
    getMsgCase() {
      return MsgCase.forNumber(
          msgCase_);
    }

    public static final int ACKNOWLEDGEENROLLMENTMSG_FIELD_NUMBER = 1;
    /**
     * <code>.AcknowledgeEnrollment AcknowledgeEnrollmentMsg = 1;</code>
     */
    public boolean hasAcknowledgeEnrollmentMsg() {
      return msgCase_ == 1;
    }
    /**
     * <code>.AcknowledgeEnrollment AcknowledgeEnrollmentMsg = 1;</code>
     */
    public edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeEnrollment getAcknowledgeEnrollmentMsg() {
      if (msgCase_ == 1) {
         return (edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeEnrollment) msg_;
      }
      return edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeEnrollment.getDefaultInstance();
    }
    /**
     * <code>.AcknowledgeEnrollment AcknowledgeEnrollmentMsg = 1;</code>
     */
    public edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeEnrollmentOrBuilder getAcknowledgeEnrollmentMsgOrBuilder() {
      if (msgCase_ == 1) {
         return (edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeEnrollment) msg_;
      }
      return edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeEnrollment.getDefaultInstance();
    }

    public static final int ACKNOWLEDGEREADINESSTOSNMSG_FIELD_NUMBER = 2;
    /**
     * <code>.AcknowledgeReadinessToSN AcknowledgeReadinessToSNMsg = 2;</code>
     */
    public boolean hasAcknowledgeReadinessToSNMsg() {
      return msgCase_ == 2;
    }
    /**
     * <code>.AcknowledgeReadinessToSN AcknowledgeReadinessToSNMsg = 2;</code>
     */
    public edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeReadinessToSN getAcknowledgeReadinessToSNMsg() {
      if (msgCase_ == 2) {
         return (edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeReadinessToSN) msg_;
      }
      return edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeReadinessToSN.getDefaultInstance();
    }
    /**
     * <code>.AcknowledgeReadinessToSN AcknowledgeReadinessToSNMsg = 2;</code>
     */
    public edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeReadinessToSNOrBuilder getAcknowledgeReadinessToSNMsgOrBuilder() {
      if (msgCase_ == 2) {
         return (edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeReadinessToSN) msg_;
      }
      return edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeReadinessToSN.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (msgCase_ == 1) {
        output.writeMessage(1, (edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeEnrollment) msg_);
      }
      if (msgCase_ == 2) {
        output.writeMessage(2, (edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeReadinessToSN) msg_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (msgCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, (edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeEnrollment) msg_);
      }
      if (msgCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeReadinessToSN) msg_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof edu.usfca.cs.dfs.ResponsesToStorageNode.ResponsesToStorageNodeWrapper)) {
        return super.equals(obj);
      }
      edu.usfca.cs.dfs.ResponsesToStorageNode.ResponsesToStorageNodeWrapper other = (edu.usfca.cs.dfs.ResponsesToStorageNode.ResponsesToStorageNodeWrapper) obj;

      boolean result = true;
      result = result && getMsgCase().equals(
          other.getMsgCase());
      if (!result) return false;
      switch (msgCase_) {
        case 1:
          result = result && getAcknowledgeEnrollmentMsg()
              .equals(other.getAcknowledgeEnrollmentMsg());
          break;
        case 2:
          result = result && getAcknowledgeReadinessToSNMsg()
              .equals(other.getAcknowledgeReadinessToSNMsg());
          break;
        case 0:
        default:
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      switch (msgCase_) {
        case 1:
          hash = (37 * hash) + ACKNOWLEDGEENROLLMENTMSG_FIELD_NUMBER;
          hash = (53 * hash) + getAcknowledgeEnrollmentMsg().hashCode();
          break;
        case 2:
          hash = (37 * hash) + ACKNOWLEDGEREADINESSTOSNMSG_FIELD_NUMBER;
          hash = (53 * hash) + getAcknowledgeReadinessToSNMsg().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static edu.usfca.cs.dfs.ResponsesToStorageNode.ResponsesToStorageNodeWrapper parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usfca.cs.dfs.ResponsesToStorageNode.ResponsesToStorageNodeWrapper parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.ResponsesToStorageNode.ResponsesToStorageNodeWrapper parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usfca.cs.dfs.ResponsesToStorageNode.ResponsesToStorageNodeWrapper parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.ResponsesToStorageNode.ResponsesToStorageNodeWrapper parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usfca.cs.dfs.ResponsesToStorageNode.ResponsesToStorageNodeWrapper parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.ResponsesToStorageNode.ResponsesToStorageNodeWrapper parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.usfca.cs.dfs.ResponsesToStorageNode.ResponsesToStorageNodeWrapper parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.ResponsesToStorageNode.ResponsesToStorageNodeWrapper parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static edu.usfca.cs.dfs.ResponsesToStorageNode.ResponsesToStorageNodeWrapper parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.ResponsesToStorageNode.ResponsesToStorageNodeWrapper parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.usfca.cs.dfs.ResponsesToStorageNode.ResponsesToStorageNodeWrapper parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(edu.usfca.cs.dfs.ResponsesToStorageNode.ResponsesToStorageNodeWrapper prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ResponsesToStorageNodeWrapper}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ResponsesToStorageNodeWrapper)
        edu.usfca.cs.dfs.ResponsesToStorageNode.ResponsesToStorageNodeWrapperOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.usfca.cs.dfs.ResponsesToStorageNode.internal_static_ResponsesToStorageNodeWrapper_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.usfca.cs.dfs.ResponsesToStorageNode.internal_static_ResponsesToStorageNodeWrapper_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.usfca.cs.dfs.ResponsesToStorageNode.ResponsesToStorageNodeWrapper.class, edu.usfca.cs.dfs.ResponsesToStorageNode.ResponsesToStorageNodeWrapper.Builder.class);
      }

      // Construct using edu.usfca.cs.dfs.ResponsesToStorageNode.ResponsesToStorageNodeWrapper.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        msgCase_ = 0;
        msg_ = null;
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.usfca.cs.dfs.ResponsesToStorageNode.internal_static_ResponsesToStorageNodeWrapper_descriptor;
      }

      public edu.usfca.cs.dfs.ResponsesToStorageNode.ResponsesToStorageNodeWrapper getDefaultInstanceForType() {
        return edu.usfca.cs.dfs.ResponsesToStorageNode.ResponsesToStorageNodeWrapper.getDefaultInstance();
      }

      public edu.usfca.cs.dfs.ResponsesToStorageNode.ResponsesToStorageNodeWrapper build() {
        edu.usfca.cs.dfs.ResponsesToStorageNode.ResponsesToStorageNodeWrapper result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public edu.usfca.cs.dfs.ResponsesToStorageNode.ResponsesToStorageNodeWrapper buildPartial() {
        edu.usfca.cs.dfs.ResponsesToStorageNode.ResponsesToStorageNodeWrapper result = new edu.usfca.cs.dfs.ResponsesToStorageNode.ResponsesToStorageNodeWrapper(this);
        if (msgCase_ == 1) {
          if (acknowledgeEnrollmentMsgBuilder_ == null) {
            result.msg_ = msg_;
          } else {
            result.msg_ = acknowledgeEnrollmentMsgBuilder_.build();
          }
        }
        if (msgCase_ == 2) {
          if (acknowledgeReadinessToSNMsgBuilder_ == null) {
            result.msg_ = msg_;
          } else {
            result.msg_ = acknowledgeReadinessToSNMsgBuilder_.build();
          }
        }
        result.msgCase_ = msgCase_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.usfca.cs.dfs.ResponsesToStorageNode.ResponsesToStorageNodeWrapper) {
          return mergeFrom((edu.usfca.cs.dfs.ResponsesToStorageNode.ResponsesToStorageNodeWrapper)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.usfca.cs.dfs.ResponsesToStorageNode.ResponsesToStorageNodeWrapper other) {
        if (other == edu.usfca.cs.dfs.ResponsesToStorageNode.ResponsesToStorageNodeWrapper.getDefaultInstance()) return this;
        switch (other.getMsgCase()) {
          case ACKNOWLEDGEENROLLMENTMSG: {
            mergeAcknowledgeEnrollmentMsg(other.getAcknowledgeEnrollmentMsg());
            break;
          }
          case ACKNOWLEDGEREADINESSTOSNMSG: {
            mergeAcknowledgeReadinessToSNMsg(other.getAcknowledgeReadinessToSNMsg());
            break;
          }
          case MSG_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        edu.usfca.cs.dfs.ResponsesToStorageNode.ResponsesToStorageNodeWrapper parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (edu.usfca.cs.dfs.ResponsesToStorageNode.ResponsesToStorageNodeWrapper) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int msgCase_ = 0;
      private java.lang.Object msg_;
      public MsgCase
          getMsgCase() {
        return MsgCase.forNumber(
            msgCase_);
      }

      public Builder clearMsg() {
        msgCase_ = 0;
        msg_ = null;
        onChanged();
        return this;
      }


      private com.google.protobuf.SingleFieldBuilderV3<
          edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeEnrollment, edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeEnrollment.Builder, edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeEnrollmentOrBuilder> acknowledgeEnrollmentMsgBuilder_;
      /**
       * <code>.AcknowledgeEnrollment AcknowledgeEnrollmentMsg = 1;</code>
       */
      public boolean hasAcknowledgeEnrollmentMsg() {
        return msgCase_ == 1;
      }
      /**
       * <code>.AcknowledgeEnrollment AcknowledgeEnrollmentMsg = 1;</code>
       */
      public edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeEnrollment getAcknowledgeEnrollmentMsg() {
        if (acknowledgeEnrollmentMsgBuilder_ == null) {
          if (msgCase_ == 1) {
            return (edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeEnrollment) msg_;
          }
          return edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeEnrollment.getDefaultInstance();
        } else {
          if (msgCase_ == 1) {
            return acknowledgeEnrollmentMsgBuilder_.getMessage();
          }
          return edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeEnrollment.getDefaultInstance();
        }
      }
      /**
       * <code>.AcknowledgeEnrollment AcknowledgeEnrollmentMsg = 1;</code>
       */
      public Builder setAcknowledgeEnrollmentMsg(edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeEnrollment value) {
        if (acknowledgeEnrollmentMsgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          msg_ = value;
          onChanged();
        } else {
          acknowledgeEnrollmentMsgBuilder_.setMessage(value);
        }
        msgCase_ = 1;
        return this;
      }
      /**
       * <code>.AcknowledgeEnrollment AcknowledgeEnrollmentMsg = 1;</code>
       */
      public Builder setAcknowledgeEnrollmentMsg(
          edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeEnrollment.Builder builderForValue) {
        if (acknowledgeEnrollmentMsgBuilder_ == null) {
          msg_ = builderForValue.build();
          onChanged();
        } else {
          acknowledgeEnrollmentMsgBuilder_.setMessage(builderForValue.build());
        }
        msgCase_ = 1;
        return this;
      }
      /**
       * <code>.AcknowledgeEnrollment AcknowledgeEnrollmentMsg = 1;</code>
       */
      public Builder mergeAcknowledgeEnrollmentMsg(edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeEnrollment value) {
        if (acknowledgeEnrollmentMsgBuilder_ == null) {
          if (msgCase_ == 1 &&
              msg_ != edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeEnrollment.getDefaultInstance()) {
            msg_ = edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeEnrollment.newBuilder((edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeEnrollment) msg_)
                .mergeFrom(value).buildPartial();
          } else {
            msg_ = value;
          }
          onChanged();
        } else {
          if (msgCase_ == 1) {
            acknowledgeEnrollmentMsgBuilder_.mergeFrom(value);
          }
          acknowledgeEnrollmentMsgBuilder_.setMessage(value);
        }
        msgCase_ = 1;
        return this;
      }
      /**
       * <code>.AcknowledgeEnrollment AcknowledgeEnrollmentMsg = 1;</code>
       */
      public Builder clearAcknowledgeEnrollmentMsg() {
        if (acknowledgeEnrollmentMsgBuilder_ == null) {
          if (msgCase_ == 1) {
            msgCase_ = 0;
            msg_ = null;
            onChanged();
          }
        } else {
          if (msgCase_ == 1) {
            msgCase_ = 0;
            msg_ = null;
          }
          acknowledgeEnrollmentMsgBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.AcknowledgeEnrollment AcknowledgeEnrollmentMsg = 1;</code>
       */
      public edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeEnrollment.Builder getAcknowledgeEnrollmentMsgBuilder() {
        return getAcknowledgeEnrollmentMsgFieldBuilder().getBuilder();
      }
      /**
       * <code>.AcknowledgeEnrollment AcknowledgeEnrollmentMsg = 1;</code>
       */
      public edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeEnrollmentOrBuilder getAcknowledgeEnrollmentMsgOrBuilder() {
        if ((msgCase_ == 1) && (acknowledgeEnrollmentMsgBuilder_ != null)) {
          return acknowledgeEnrollmentMsgBuilder_.getMessageOrBuilder();
        } else {
          if (msgCase_ == 1) {
            return (edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeEnrollment) msg_;
          }
          return edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeEnrollment.getDefaultInstance();
        }
      }
      /**
       * <code>.AcknowledgeEnrollment AcknowledgeEnrollmentMsg = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeEnrollment, edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeEnrollment.Builder, edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeEnrollmentOrBuilder> 
          getAcknowledgeEnrollmentMsgFieldBuilder() {
        if (acknowledgeEnrollmentMsgBuilder_ == null) {
          if (!(msgCase_ == 1)) {
            msg_ = edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeEnrollment.getDefaultInstance();
          }
          acknowledgeEnrollmentMsgBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeEnrollment, edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeEnrollment.Builder, edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeEnrollmentOrBuilder>(
                  (edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeEnrollment) msg_,
                  getParentForChildren(),
                  isClean());
          msg_ = null;
        }
        msgCase_ = 1;
        onChanged();;
        return acknowledgeEnrollmentMsgBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeReadinessToSN, edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeReadinessToSN.Builder, edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeReadinessToSNOrBuilder> acknowledgeReadinessToSNMsgBuilder_;
      /**
       * <code>.AcknowledgeReadinessToSN AcknowledgeReadinessToSNMsg = 2;</code>
       */
      public boolean hasAcknowledgeReadinessToSNMsg() {
        return msgCase_ == 2;
      }
      /**
       * <code>.AcknowledgeReadinessToSN AcknowledgeReadinessToSNMsg = 2;</code>
       */
      public edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeReadinessToSN getAcknowledgeReadinessToSNMsg() {
        if (acknowledgeReadinessToSNMsgBuilder_ == null) {
          if (msgCase_ == 2) {
            return (edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeReadinessToSN) msg_;
          }
          return edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeReadinessToSN.getDefaultInstance();
        } else {
          if (msgCase_ == 2) {
            return acknowledgeReadinessToSNMsgBuilder_.getMessage();
          }
          return edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeReadinessToSN.getDefaultInstance();
        }
      }
      /**
       * <code>.AcknowledgeReadinessToSN AcknowledgeReadinessToSNMsg = 2;</code>
       */
      public Builder setAcknowledgeReadinessToSNMsg(edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeReadinessToSN value) {
        if (acknowledgeReadinessToSNMsgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          msg_ = value;
          onChanged();
        } else {
          acknowledgeReadinessToSNMsgBuilder_.setMessage(value);
        }
        msgCase_ = 2;
        return this;
      }
      /**
       * <code>.AcknowledgeReadinessToSN AcknowledgeReadinessToSNMsg = 2;</code>
       */
      public Builder setAcknowledgeReadinessToSNMsg(
          edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeReadinessToSN.Builder builderForValue) {
        if (acknowledgeReadinessToSNMsgBuilder_ == null) {
          msg_ = builderForValue.build();
          onChanged();
        } else {
          acknowledgeReadinessToSNMsgBuilder_.setMessage(builderForValue.build());
        }
        msgCase_ = 2;
        return this;
      }
      /**
       * <code>.AcknowledgeReadinessToSN AcknowledgeReadinessToSNMsg = 2;</code>
       */
      public Builder mergeAcknowledgeReadinessToSNMsg(edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeReadinessToSN value) {
        if (acknowledgeReadinessToSNMsgBuilder_ == null) {
          if (msgCase_ == 2 &&
              msg_ != edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeReadinessToSN.getDefaultInstance()) {
            msg_ = edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeReadinessToSN.newBuilder((edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeReadinessToSN) msg_)
                .mergeFrom(value).buildPartial();
          } else {
            msg_ = value;
          }
          onChanged();
        } else {
          if (msgCase_ == 2) {
            acknowledgeReadinessToSNMsgBuilder_.mergeFrom(value);
          }
          acknowledgeReadinessToSNMsgBuilder_.setMessage(value);
        }
        msgCase_ = 2;
        return this;
      }
      /**
       * <code>.AcknowledgeReadinessToSN AcknowledgeReadinessToSNMsg = 2;</code>
       */
      public Builder clearAcknowledgeReadinessToSNMsg() {
        if (acknowledgeReadinessToSNMsgBuilder_ == null) {
          if (msgCase_ == 2) {
            msgCase_ = 0;
            msg_ = null;
            onChanged();
          }
        } else {
          if (msgCase_ == 2) {
            msgCase_ = 0;
            msg_ = null;
          }
          acknowledgeReadinessToSNMsgBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.AcknowledgeReadinessToSN AcknowledgeReadinessToSNMsg = 2;</code>
       */
      public edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeReadinessToSN.Builder getAcknowledgeReadinessToSNMsgBuilder() {
        return getAcknowledgeReadinessToSNMsgFieldBuilder().getBuilder();
      }
      /**
       * <code>.AcknowledgeReadinessToSN AcknowledgeReadinessToSNMsg = 2;</code>
       */
      public edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeReadinessToSNOrBuilder getAcknowledgeReadinessToSNMsgOrBuilder() {
        if ((msgCase_ == 2) && (acknowledgeReadinessToSNMsgBuilder_ != null)) {
          return acknowledgeReadinessToSNMsgBuilder_.getMessageOrBuilder();
        } else {
          if (msgCase_ == 2) {
            return (edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeReadinessToSN) msg_;
          }
          return edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeReadinessToSN.getDefaultInstance();
        }
      }
      /**
       * <code>.AcknowledgeReadinessToSN AcknowledgeReadinessToSNMsg = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeReadinessToSN, edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeReadinessToSN.Builder, edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeReadinessToSNOrBuilder> 
          getAcknowledgeReadinessToSNMsgFieldBuilder() {
        if (acknowledgeReadinessToSNMsgBuilder_ == null) {
          if (!(msgCase_ == 2)) {
            msg_ = edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeReadinessToSN.getDefaultInstance();
          }
          acknowledgeReadinessToSNMsgBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeReadinessToSN, edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeReadinessToSN.Builder, edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeReadinessToSNOrBuilder>(
                  (edu.usfca.cs.dfs.ResponsesToStorageNode.AcknowledgeReadinessToSN) msg_,
                  getParentForChildren(),
                  isClean());
          msg_ = null;
        }
        msgCase_ = 2;
        onChanged();;
        return acknowledgeReadinessToSNMsgBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ResponsesToStorageNodeWrapper)
    }

    // @@protoc_insertion_point(class_scope:ResponsesToStorageNodeWrapper)
    private static final edu.usfca.cs.dfs.ResponsesToStorageNode.ResponsesToStorageNodeWrapper DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new edu.usfca.cs.dfs.ResponsesToStorageNode.ResponsesToStorageNodeWrapper();
    }

    public static edu.usfca.cs.dfs.ResponsesToStorageNode.ResponsesToStorageNodeWrapper getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResponsesToStorageNodeWrapper>
        PARSER = new com.google.protobuf.AbstractParser<ResponsesToStorageNodeWrapper>() {
      public ResponsesToStorageNodeWrapper parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ResponsesToStorageNodeWrapper(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ResponsesToStorageNodeWrapper> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ResponsesToStorageNodeWrapper> getParserForType() {
      return PARSER;
    }

    public edu.usfca.cs.dfs.ResponsesToStorageNode.ResponsesToStorageNodeWrapper getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AcknowledgeEnrollment_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AcknowledgeEnrollment_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AcknowledgeReadinessToSN_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AcknowledgeReadinessToSN_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResponsesToStorageNodeWrapper_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ResponsesToStorageNodeWrapper_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036responses_to_storageNode.proto\"(\n\025Ackn" +
      "owledgeEnrollment\022\017\n\007success\030\001 \001(\010\"+\n\030Ac" +
      "knowledgeReadinessToSN\022\017\n\007success\030\001 \001(\010\"" +
      "\244\001\n\035ResponsesToStorageNodeWrapper\022:\n\030Ack" +
      "nowledgeEnrollmentMsg\030\001 \001(\0132\026.Acknowledg" +
      "eEnrollmentH\000\022@\n\033AcknowledgeReadinessToS" +
      "NMsg\030\002 \001(\0132\031.AcknowledgeReadinessToSNH\000B" +
      "\005\n\003msgB\022\n\020edu.usfca.cs.dfsb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_AcknowledgeEnrollment_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_AcknowledgeEnrollment_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AcknowledgeEnrollment_descriptor,
        new java.lang.String[] { "Success", });
    internal_static_AcknowledgeReadinessToSN_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_AcknowledgeReadinessToSN_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AcknowledgeReadinessToSN_descriptor,
        new java.lang.String[] { "Success", });
    internal_static_ResponsesToStorageNodeWrapper_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ResponsesToStorageNodeWrapper_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ResponsesToStorageNodeWrapper_descriptor,
        new java.lang.String[] { "AcknowledgeEnrollmentMsg", "AcknowledgeReadinessToSNMsg", "Msg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
