// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: status.proto

package edu.usfca.cs.dfs;

public final class Status {
  private Status() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface receivedStatusOrBuilder extends
      // @@protoc_insertion_point(interface_extends:receivedStatus)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool success = 1;</code>
     */
    boolean getSuccess();
  }
  /**
   * Protobuf type {@code receivedStatus}
   */
  public  static final class receivedStatus extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:receivedStatus)
      receivedStatusOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use receivedStatus.newBuilder() to construct.
    private receivedStatus(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private receivedStatus() {
      success_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private receivedStatus(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              success_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.usfca.cs.dfs.Status.internal_static_receivedStatus_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.usfca.cs.dfs.Status.internal_static_receivedStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.usfca.cs.dfs.Status.receivedStatus.class, edu.usfca.cs.dfs.Status.receivedStatus.Builder.class);
    }

    public static final int SUCCESS_FIELD_NUMBER = 1;
    private boolean success_;
    /**
     * <code>bool success = 1;</code>
     */
    public boolean getSuccess() {
      return success_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (success_ != false) {
        output.writeBool(1, success_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (success_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, success_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof edu.usfca.cs.dfs.Status.receivedStatus)) {
        return super.equals(obj);
      }
      edu.usfca.cs.dfs.Status.receivedStatus other = (edu.usfca.cs.dfs.Status.receivedStatus) obj;

      boolean result = true;
      result = result && (getSuccess()
          == other.getSuccess());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getSuccess());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static edu.usfca.cs.dfs.Status.receivedStatus parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usfca.cs.dfs.Status.receivedStatus parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.Status.receivedStatus parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usfca.cs.dfs.Status.receivedStatus parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.Status.receivedStatus parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usfca.cs.dfs.Status.receivedStatus parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.Status.receivedStatus parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.usfca.cs.dfs.Status.receivedStatus parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.Status.receivedStatus parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static edu.usfca.cs.dfs.Status.receivedStatus parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.Status.receivedStatus parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.usfca.cs.dfs.Status.receivedStatus parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(edu.usfca.cs.dfs.Status.receivedStatus prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code receivedStatus}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:receivedStatus)
        edu.usfca.cs.dfs.Status.receivedStatusOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.usfca.cs.dfs.Status.internal_static_receivedStatus_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.usfca.cs.dfs.Status.internal_static_receivedStatus_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.usfca.cs.dfs.Status.receivedStatus.class, edu.usfca.cs.dfs.Status.receivedStatus.Builder.class);
      }

      // Construct using edu.usfca.cs.dfs.Status.receivedStatus.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        success_ = false;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.usfca.cs.dfs.Status.internal_static_receivedStatus_descriptor;
      }

      public edu.usfca.cs.dfs.Status.receivedStatus getDefaultInstanceForType() {
        return edu.usfca.cs.dfs.Status.receivedStatus.getDefaultInstance();
      }

      public edu.usfca.cs.dfs.Status.receivedStatus build() {
        edu.usfca.cs.dfs.Status.receivedStatus result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public edu.usfca.cs.dfs.Status.receivedStatus buildPartial() {
        edu.usfca.cs.dfs.Status.receivedStatus result = new edu.usfca.cs.dfs.Status.receivedStatus(this);
        result.success_ = success_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.usfca.cs.dfs.Status.receivedStatus) {
          return mergeFrom((edu.usfca.cs.dfs.Status.receivedStatus)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.usfca.cs.dfs.Status.receivedStatus other) {
        if (other == edu.usfca.cs.dfs.Status.receivedStatus.getDefaultInstance()) return this;
        if (other.getSuccess() != false) {
          setSuccess(other.getSuccess());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        edu.usfca.cs.dfs.Status.receivedStatus parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (edu.usfca.cs.dfs.Status.receivedStatus) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean success_ ;
      /**
       * <code>bool success = 1;</code>
       */
      public boolean getSuccess() {
        return success_;
      }
      /**
       * <code>bool success = 1;</code>
       */
      public Builder setSuccess(boolean value) {
        
        success_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool success = 1;</code>
       */
      public Builder clearSuccess() {
        
        success_ = false;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:receivedStatus)
    }

    // @@protoc_insertion_point(class_scope:receivedStatus)
    private static final edu.usfca.cs.dfs.Status.receivedStatus DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new edu.usfca.cs.dfs.Status.receivedStatus();
    }

    public static edu.usfca.cs.dfs.Status.receivedStatus getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<receivedStatus>
        PARSER = new com.google.protobuf.AbstractParser<receivedStatus>() {
      public receivedStatus parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new receivedStatus(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<receivedStatus> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<receivedStatus> getParserForType() {
      return PARSER;
    }

    public edu.usfca.cs.dfs.Status.receivedStatus getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface retrieveChunkdataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:retrieveChunkdata)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string filename = 1;</code>
     */
    java.lang.String getFilename();
    /**
     * <code>string filename = 1;</code>
     */
    com.google.protobuf.ByteString
        getFilenameBytes();

    /**
     * <code>bytes data = 2;</code>
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code retrieveChunkdata}
   */
  public  static final class retrieveChunkdata extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:retrieveChunkdata)
      retrieveChunkdataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use retrieveChunkdata.newBuilder() to construct.
    private retrieveChunkdata(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private retrieveChunkdata() {
      filename_ = "";
      data_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private retrieveChunkdata(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              filename_ = s;
              break;
            }
            case 18: {

              data_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.usfca.cs.dfs.Status.internal_static_retrieveChunkdata_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.usfca.cs.dfs.Status.internal_static_retrieveChunkdata_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.usfca.cs.dfs.Status.retrieveChunkdata.class, edu.usfca.cs.dfs.Status.retrieveChunkdata.Builder.class);
    }

    public static final int FILENAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object filename_;
    /**
     * <code>string filename = 1;</code>
     */
    public java.lang.String getFilename() {
      java.lang.Object ref = filename_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        filename_ = s;
        return s;
      }
    }
    /**
     * <code>string filename = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFilenameBytes() {
      java.lang.Object ref = filename_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        filename_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>bytes data = 2;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getFilenameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, filename_);
      }
      if (!data_.isEmpty()) {
        output.writeBytes(2, data_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getFilenameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, filename_);
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, data_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof edu.usfca.cs.dfs.Status.retrieveChunkdata)) {
        return super.equals(obj);
      }
      edu.usfca.cs.dfs.Status.retrieveChunkdata other = (edu.usfca.cs.dfs.Status.retrieveChunkdata) obj;

      boolean result = true;
      result = result && getFilename()
          .equals(other.getFilename());
      result = result && getData()
          .equals(other.getData());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FILENAME_FIELD_NUMBER;
      hash = (53 * hash) + getFilename().hashCode();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static edu.usfca.cs.dfs.Status.retrieveChunkdata parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usfca.cs.dfs.Status.retrieveChunkdata parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.Status.retrieveChunkdata parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usfca.cs.dfs.Status.retrieveChunkdata parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.Status.retrieveChunkdata parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usfca.cs.dfs.Status.retrieveChunkdata parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.Status.retrieveChunkdata parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.usfca.cs.dfs.Status.retrieveChunkdata parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.Status.retrieveChunkdata parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static edu.usfca.cs.dfs.Status.retrieveChunkdata parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.Status.retrieveChunkdata parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.usfca.cs.dfs.Status.retrieveChunkdata parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(edu.usfca.cs.dfs.Status.retrieveChunkdata prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code retrieveChunkdata}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:retrieveChunkdata)
        edu.usfca.cs.dfs.Status.retrieveChunkdataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.usfca.cs.dfs.Status.internal_static_retrieveChunkdata_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.usfca.cs.dfs.Status.internal_static_retrieveChunkdata_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.usfca.cs.dfs.Status.retrieveChunkdata.class, edu.usfca.cs.dfs.Status.retrieveChunkdata.Builder.class);
      }

      // Construct using edu.usfca.cs.dfs.Status.retrieveChunkdata.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        filename_ = "";

        data_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.usfca.cs.dfs.Status.internal_static_retrieveChunkdata_descriptor;
      }

      public edu.usfca.cs.dfs.Status.retrieveChunkdata getDefaultInstanceForType() {
        return edu.usfca.cs.dfs.Status.retrieveChunkdata.getDefaultInstance();
      }

      public edu.usfca.cs.dfs.Status.retrieveChunkdata build() {
        edu.usfca.cs.dfs.Status.retrieveChunkdata result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public edu.usfca.cs.dfs.Status.retrieveChunkdata buildPartial() {
        edu.usfca.cs.dfs.Status.retrieveChunkdata result = new edu.usfca.cs.dfs.Status.retrieveChunkdata(this);
        result.filename_ = filename_;
        result.data_ = data_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.usfca.cs.dfs.Status.retrieveChunkdata) {
          return mergeFrom((edu.usfca.cs.dfs.Status.retrieveChunkdata)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.usfca.cs.dfs.Status.retrieveChunkdata other) {
        if (other == edu.usfca.cs.dfs.Status.retrieveChunkdata.getDefaultInstance()) return this;
        if (!other.getFilename().isEmpty()) {
          filename_ = other.filename_;
          onChanged();
        }
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        edu.usfca.cs.dfs.Status.retrieveChunkdata parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (edu.usfca.cs.dfs.Status.retrieveChunkdata) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object filename_ = "";
      /**
       * <code>string filename = 1;</code>
       */
      public java.lang.String getFilename() {
        java.lang.Object ref = filename_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          filename_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string filename = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFilenameBytes() {
        java.lang.Object ref = filename_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          filename_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string filename = 1;</code>
       */
      public Builder setFilename(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        filename_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string filename = 1;</code>
       */
      public Builder clearFilename() {
        
        filename_ = getDefaultInstance().getFilename();
        onChanged();
        return this;
      }
      /**
       * <code>string filename = 1;</code>
       */
      public Builder setFilenameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        filename_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes data = 2;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>bytes data = 2;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes data = 2;</code>
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:retrieveChunkdata)
    }

    // @@protoc_insertion_point(class_scope:retrieveChunkdata)
    private static final edu.usfca.cs.dfs.Status.retrieveChunkdata DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new edu.usfca.cs.dfs.Status.retrieveChunkdata();
    }

    public static edu.usfca.cs.dfs.Status.retrieveChunkdata getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<retrieveChunkdata>
        PARSER = new com.google.protobuf.AbstractParser<retrieveChunkdata>() {
      public retrieveChunkdata parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new retrieveChunkdata(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<retrieveChunkdata> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<retrieveChunkdata> getParserForType() {
      return PARSER;
    }

    public edu.usfca.cs.dfs.Status.retrieveChunkdata getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface StorageMessageWrapperOrBuilder extends
      // @@protoc_insertion_point(interface_extends:StorageMessageWrapper)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.receivedStatus recvStatus = 1;</code>
     */
    boolean hasRecvStatus();
    /**
     * <code>.receivedStatus recvStatus = 1;</code>
     */
    edu.usfca.cs.dfs.Status.receivedStatus getRecvStatus();
    /**
     * <code>.receivedStatus recvStatus = 1;</code>
     */
    edu.usfca.cs.dfs.Status.receivedStatusOrBuilder getRecvStatusOrBuilder();

    /**
     * <code>.retrieveChunkdata retrvChunkdata = 2;</code>
     */
    boolean hasRetrvChunkdata();
    /**
     * <code>.retrieveChunkdata retrvChunkdata = 2;</code>
     */
    edu.usfca.cs.dfs.Status.retrieveChunkdata getRetrvChunkdata();
    /**
     * <code>.retrieveChunkdata retrvChunkdata = 2;</code>
     */
    edu.usfca.cs.dfs.Status.retrieveChunkdataOrBuilder getRetrvChunkdataOrBuilder();
  }
  /**
   * Protobuf type {@code StorageMessageWrapper}
   */
  public  static final class StorageMessageWrapper extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:StorageMessageWrapper)
      StorageMessageWrapperOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use StorageMessageWrapper.newBuilder() to construct.
    private StorageMessageWrapper(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private StorageMessageWrapper() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private StorageMessageWrapper(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              edu.usfca.cs.dfs.Status.receivedStatus.Builder subBuilder = null;
              if (recvStatus_ != null) {
                subBuilder = recvStatus_.toBuilder();
              }
              recvStatus_ = input.readMessage(edu.usfca.cs.dfs.Status.receivedStatus.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(recvStatus_);
                recvStatus_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              edu.usfca.cs.dfs.Status.retrieveChunkdata.Builder subBuilder = null;
              if (retrvChunkdata_ != null) {
                subBuilder = retrvChunkdata_.toBuilder();
              }
              retrvChunkdata_ = input.readMessage(edu.usfca.cs.dfs.Status.retrieveChunkdata.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(retrvChunkdata_);
                retrvChunkdata_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.usfca.cs.dfs.Status.internal_static_StorageMessageWrapper_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.usfca.cs.dfs.Status.internal_static_StorageMessageWrapper_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.usfca.cs.dfs.Status.StorageMessageWrapper.class, edu.usfca.cs.dfs.Status.StorageMessageWrapper.Builder.class);
    }

    public static final int RECVSTATUS_FIELD_NUMBER = 1;
    private edu.usfca.cs.dfs.Status.receivedStatus recvStatus_;
    /**
     * <code>.receivedStatus recvStatus = 1;</code>
     */
    public boolean hasRecvStatus() {
      return recvStatus_ != null;
    }
    /**
     * <code>.receivedStatus recvStatus = 1;</code>
     */
    public edu.usfca.cs.dfs.Status.receivedStatus getRecvStatus() {
      return recvStatus_ == null ? edu.usfca.cs.dfs.Status.receivedStatus.getDefaultInstance() : recvStatus_;
    }
    /**
     * <code>.receivedStatus recvStatus = 1;</code>
     */
    public edu.usfca.cs.dfs.Status.receivedStatusOrBuilder getRecvStatusOrBuilder() {
      return getRecvStatus();
    }

    public static final int RETRVCHUNKDATA_FIELD_NUMBER = 2;
    private edu.usfca.cs.dfs.Status.retrieveChunkdata retrvChunkdata_;
    /**
     * <code>.retrieveChunkdata retrvChunkdata = 2;</code>
     */
    public boolean hasRetrvChunkdata() {
      return retrvChunkdata_ != null;
    }
    /**
     * <code>.retrieveChunkdata retrvChunkdata = 2;</code>
     */
    public edu.usfca.cs.dfs.Status.retrieveChunkdata getRetrvChunkdata() {
      return retrvChunkdata_ == null ? edu.usfca.cs.dfs.Status.retrieveChunkdata.getDefaultInstance() : retrvChunkdata_;
    }
    /**
     * <code>.retrieveChunkdata retrvChunkdata = 2;</code>
     */
    public edu.usfca.cs.dfs.Status.retrieveChunkdataOrBuilder getRetrvChunkdataOrBuilder() {
      return getRetrvChunkdata();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (recvStatus_ != null) {
        output.writeMessage(1, getRecvStatus());
      }
      if (retrvChunkdata_ != null) {
        output.writeMessage(2, getRetrvChunkdata());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (recvStatus_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getRecvStatus());
      }
      if (retrvChunkdata_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getRetrvChunkdata());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof edu.usfca.cs.dfs.Status.StorageMessageWrapper)) {
        return super.equals(obj);
      }
      edu.usfca.cs.dfs.Status.StorageMessageWrapper other = (edu.usfca.cs.dfs.Status.StorageMessageWrapper) obj;

      boolean result = true;
      result = result && (hasRecvStatus() == other.hasRecvStatus());
      if (hasRecvStatus()) {
        result = result && getRecvStatus()
            .equals(other.getRecvStatus());
      }
      result = result && (hasRetrvChunkdata() == other.hasRetrvChunkdata());
      if (hasRetrvChunkdata()) {
        result = result && getRetrvChunkdata()
            .equals(other.getRetrvChunkdata());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasRecvStatus()) {
        hash = (37 * hash) + RECVSTATUS_FIELD_NUMBER;
        hash = (53 * hash) + getRecvStatus().hashCode();
      }
      if (hasRetrvChunkdata()) {
        hash = (37 * hash) + RETRVCHUNKDATA_FIELD_NUMBER;
        hash = (53 * hash) + getRetrvChunkdata().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static edu.usfca.cs.dfs.Status.StorageMessageWrapper parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usfca.cs.dfs.Status.StorageMessageWrapper parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.Status.StorageMessageWrapper parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usfca.cs.dfs.Status.StorageMessageWrapper parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.Status.StorageMessageWrapper parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usfca.cs.dfs.Status.StorageMessageWrapper parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.Status.StorageMessageWrapper parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.usfca.cs.dfs.Status.StorageMessageWrapper parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.Status.StorageMessageWrapper parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static edu.usfca.cs.dfs.Status.StorageMessageWrapper parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.Status.StorageMessageWrapper parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.usfca.cs.dfs.Status.StorageMessageWrapper parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(edu.usfca.cs.dfs.Status.StorageMessageWrapper prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code StorageMessageWrapper}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:StorageMessageWrapper)
        edu.usfca.cs.dfs.Status.StorageMessageWrapperOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.usfca.cs.dfs.Status.internal_static_StorageMessageWrapper_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.usfca.cs.dfs.Status.internal_static_StorageMessageWrapper_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.usfca.cs.dfs.Status.StorageMessageWrapper.class, edu.usfca.cs.dfs.Status.StorageMessageWrapper.Builder.class);
      }

      // Construct using edu.usfca.cs.dfs.Status.StorageMessageWrapper.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (recvStatusBuilder_ == null) {
          recvStatus_ = null;
        } else {
          recvStatus_ = null;
          recvStatusBuilder_ = null;
        }
        if (retrvChunkdataBuilder_ == null) {
          retrvChunkdata_ = null;
        } else {
          retrvChunkdata_ = null;
          retrvChunkdataBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.usfca.cs.dfs.Status.internal_static_StorageMessageWrapper_descriptor;
      }

      public edu.usfca.cs.dfs.Status.StorageMessageWrapper getDefaultInstanceForType() {
        return edu.usfca.cs.dfs.Status.StorageMessageWrapper.getDefaultInstance();
      }

      public edu.usfca.cs.dfs.Status.StorageMessageWrapper build() {
        edu.usfca.cs.dfs.Status.StorageMessageWrapper result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public edu.usfca.cs.dfs.Status.StorageMessageWrapper buildPartial() {
        edu.usfca.cs.dfs.Status.StorageMessageWrapper result = new edu.usfca.cs.dfs.Status.StorageMessageWrapper(this);
        if (recvStatusBuilder_ == null) {
          result.recvStatus_ = recvStatus_;
        } else {
          result.recvStatus_ = recvStatusBuilder_.build();
        }
        if (retrvChunkdataBuilder_ == null) {
          result.retrvChunkdata_ = retrvChunkdata_;
        } else {
          result.retrvChunkdata_ = retrvChunkdataBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.usfca.cs.dfs.Status.StorageMessageWrapper) {
          return mergeFrom((edu.usfca.cs.dfs.Status.StorageMessageWrapper)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.usfca.cs.dfs.Status.StorageMessageWrapper other) {
        if (other == edu.usfca.cs.dfs.Status.StorageMessageWrapper.getDefaultInstance()) return this;
        if (other.hasRecvStatus()) {
          mergeRecvStatus(other.getRecvStatus());
        }
        if (other.hasRetrvChunkdata()) {
          mergeRetrvChunkdata(other.getRetrvChunkdata());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        edu.usfca.cs.dfs.Status.StorageMessageWrapper parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (edu.usfca.cs.dfs.Status.StorageMessageWrapper) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private edu.usfca.cs.dfs.Status.receivedStatus recvStatus_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          edu.usfca.cs.dfs.Status.receivedStatus, edu.usfca.cs.dfs.Status.receivedStatus.Builder, edu.usfca.cs.dfs.Status.receivedStatusOrBuilder> recvStatusBuilder_;
      /**
       * <code>.receivedStatus recvStatus = 1;</code>
       */
      public boolean hasRecvStatus() {
        return recvStatusBuilder_ != null || recvStatus_ != null;
      }
      /**
       * <code>.receivedStatus recvStatus = 1;</code>
       */
      public edu.usfca.cs.dfs.Status.receivedStatus getRecvStatus() {
        if (recvStatusBuilder_ == null) {
          return recvStatus_ == null ? edu.usfca.cs.dfs.Status.receivedStatus.getDefaultInstance() : recvStatus_;
        } else {
          return recvStatusBuilder_.getMessage();
        }
      }
      /**
       * <code>.receivedStatus recvStatus = 1;</code>
       */
      public Builder setRecvStatus(edu.usfca.cs.dfs.Status.receivedStatus value) {
        if (recvStatusBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          recvStatus_ = value;
          onChanged();
        } else {
          recvStatusBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.receivedStatus recvStatus = 1;</code>
       */
      public Builder setRecvStatus(
          edu.usfca.cs.dfs.Status.receivedStatus.Builder builderForValue) {
        if (recvStatusBuilder_ == null) {
          recvStatus_ = builderForValue.build();
          onChanged();
        } else {
          recvStatusBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.receivedStatus recvStatus = 1;</code>
       */
      public Builder mergeRecvStatus(edu.usfca.cs.dfs.Status.receivedStatus value) {
        if (recvStatusBuilder_ == null) {
          if (recvStatus_ != null) {
            recvStatus_ =
              edu.usfca.cs.dfs.Status.receivedStatus.newBuilder(recvStatus_).mergeFrom(value).buildPartial();
          } else {
            recvStatus_ = value;
          }
          onChanged();
        } else {
          recvStatusBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.receivedStatus recvStatus = 1;</code>
       */
      public Builder clearRecvStatus() {
        if (recvStatusBuilder_ == null) {
          recvStatus_ = null;
          onChanged();
        } else {
          recvStatus_ = null;
          recvStatusBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.receivedStatus recvStatus = 1;</code>
       */
      public edu.usfca.cs.dfs.Status.receivedStatus.Builder getRecvStatusBuilder() {
        
        onChanged();
        return getRecvStatusFieldBuilder().getBuilder();
      }
      /**
       * <code>.receivedStatus recvStatus = 1;</code>
       */
      public edu.usfca.cs.dfs.Status.receivedStatusOrBuilder getRecvStatusOrBuilder() {
        if (recvStatusBuilder_ != null) {
          return recvStatusBuilder_.getMessageOrBuilder();
        } else {
          return recvStatus_ == null ?
              edu.usfca.cs.dfs.Status.receivedStatus.getDefaultInstance() : recvStatus_;
        }
      }
      /**
       * <code>.receivedStatus recvStatus = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          edu.usfca.cs.dfs.Status.receivedStatus, edu.usfca.cs.dfs.Status.receivedStatus.Builder, edu.usfca.cs.dfs.Status.receivedStatusOrBuilder> 
          getRecvStatusFieldBuilder() {
        if (recvStatusBuilder_ == null) {
          recvStatusBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              edu.usfca.cs.dfs.Status.receivedStatus, edu.usfca.cs.dfs.Status.receivedStatus.Builder, edu.usfca.cs.dfs.Status.receivedStatusOrBuilder>(
                  getRecvStatus(),
                  getParentForChildren(),
                  isClean());
          recvStatus_ = null;
        }
        return recvStatusBuilder_;
      }

      private edu.usfca.cs.dfs.Status.retrieveChunkdata retrvChunkdata_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          edu.usfca.cs.dfs.Status.retrieveChunkdata, edu.usfca.cs.dfs.Status.retrieveChunkdata.Builder, edu.usfca.cs.dfs.Status.retrieveChunkdataOrBuilder> retrvChunkdataBuilder_;
      /**
       * <code>.retrieveChunkdata retrvChunkdata = 2;</code>
       */
      public boolean hasRetrvChunkdata() {
        return retrvChunkdataBuilder_ != null || retrvChunkdata_ != null;
      }
      /**
       * <code>.retrieveChunkdata retrvChunkdata = 2;</code>
       */
      public edu.usfca.cs.dfs.Status.retrieveChunkdata getRetrvChunkdata() {
        if (retrvChunkdataBuilder_ == null) {
          return retrvChunkdata_ == null ? edu.usfca.cs.dfs.Status.retrieveChunkdata.getDefaultInstance() : retrvChunkdata_;
        } else {
          return retrvChunkdataBuilder_.getMessage();
        }
      }
      /**
       * <code>.retrieveChunkdata retrvChunkdata = 2;</code>
       */
      public Builder setRetrvChunkdata(edu.usfca.cs.dfs.Status.retrieveChunkdata value) {
        if (retrvChunkdataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          retrvChunkdata_ = value;
          onChanged();
        } else {
          retrvChunkdataBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.retrieveChunkdata retrvChunkdata = 2;</code>
       */
      public Builder setRetrvChunkdata(
          edu.usfca.cs.dfs.Status.retrieveChunkdata.Builder builderForValue) {
        if (retrvChunkdataBuilder_ == null) {
          retrvChunkdata_ = builderForValue.build();
          onChanged();
        } else {
          retrvChunkdataBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.retrieveChunkdata retrvChunkdata = 2;</code>
       */
      public Builder mergeRetrvChunkdata(edu.usfca.cs.dfs.Status.retrieveChunkdata value) {
        if (retrvChunkdataBuilder_ == null) {
          if (retrvChunkdata_ != null) {
            retrvChunkdata_ =
              edu.usfca.cs.dfs.Status.retrieveChunkdata.newBuilder(retrvChunkdata_).mergeFrom(value).buildPartial();
          } else {
            retrvChunkdata_ = value;
          }
          onChanged();
        } else {
          retrvChunkdataBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.retrieveChunkdata retrvChunkdata = 2;</code>
       */
      public Builder clearRetrvChunkdata() {
        if (retrvChunkdataBuilder_ == null) {
          retrvChunkdata_ = null;
          onChanged();
        } else {
          retrvChunkdata_ = null;
          retrvChunkdataBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.retrieveChunkdata retrvChunkdata = 2;</code>
       */
      public edu.usfca.cs.dfs.Status.retrieveChunkdata.Builder getRetrvChunkdataBuilder() {
        
        onChanged();
        return getRetrvChunkdataFieldBuilder().getBuilder();
      }
      /**
       * <code>.retrieveChunkdata retrvChunkdata = 2;</code>
       */
      public edu.usfca.cs.dfs.Status.retrieveChunkdataOrBuilder getRetrvChunkdataOrBuilder() {
        if (retrvChunkdataBuilder_ != null) {
          return retrvChunkdataBuilder_.getMessageOrBuilder();
        } else {
          return retrvChunkdata_ == null ?
              edu.usfca.cs.dfs.Status.retrieveChunkdata.getDefaultInstance() : retrvChunkdata_;
        }
      }
      /**
       * <code>.retrieveChunkdata retrvChunkdata = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          edu.usfca.cs.dfs.Status.retrieveChunkdata, edu.usfca.cs.dfs.Status.retrieveChunkdata.Builder, edu.usfca.cs.dfs.Status.retrieveChunkdataOrBuilder> 
          getRetrvChunkdataFieldBuilder() {
        if (retrvChunkdataBuilder_ == null) {
          retrvChunkdataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              edu.usfca.cs.dfs.Status.retrieveChunkdata, edu.usfca.cs.dfs.Status.retrieveChunkdata.Builder, edu.usfca.cs.dfs.Status.retrieveChunkdataOrBuilder>(
                  getRetrvChunkdata(),
                  getParentForChildren(),
                  isClean());
          retrvChunkdata_ = null;
        }
        return retrvChunkdataBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:StorageMessageWrapper)
    }

    // @@protoc_insertion_point(class_scope:StorageMessageWrapper)
    private static final edu.usfca.cs.dfs.Status.StorageMessageWrapper DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new edu.usfca.cs.dfs.Status.StorageMessageWrapper();
    }

    public static edu.usfca.cs.dfs.Status.StorageMessageWrapper getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<StorageMessageWrapper>
        PARSER = new com.google.protobuf.AbstractParser<StorageMessageWrapper>() {
      public StorageMessageWrapper parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new StorageMessageWrapper(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<StorageMessageWrapper> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<StorageMessageWrapper> getParserForType() {
      return PARSER;
    }

    public edu.usfca.cs.dfs.Status.StorageMessageWrapper getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_receivedStatus_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_receivedStatus_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_retrieveChunkdata_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_retrieveChunkdata_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StorageMessageWrapper_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StorageMessageWrapper_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014status.proto\"!\n\016receivedStatus\022\017\n\007succ" +
      "ess\030\001 \001(\010\"3\n\021retrieveChunkdata\022\020\n\010filena" +
      "me\030\001 \001(\t\022\014\n\004data\030\002 \001(\014\"h\n\025StorageMessage" +
      "Wrapper\022#\n\nrecvStatus\030\001 \001(\0132\017.receivedSt" +
      "atus\022*\n\016retrvChunkdata\030\002 \001(\0132\022.retrieveC" +
      "hunkdataB\022\n\020edu.usfca.cs.dfsb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_receivedStatus_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_receivedStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_receivedStatus_descriptor,
        new java.lang.String[] { "Success", });
    internal_static_retrieveChunkdata_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_retrieveChunkdata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_retrieveChunkdata_descriptor,
        new java.lang.String[] { "Filename", "Data", });
    internal_static_StorageMessageWrapper_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_StorageMessageWrapper_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StorageMessageWrapper_descriptor,
        new java.lang.String[] { "RecvStatus", "RetrvChunkdata", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
